name: day_one
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # HTTP Client
  dio: ^5.3.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # JSON Annotation
  json_annotation: ^4.8.1
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Networking
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  
  # Utils
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
flutter:
  uses-material-design: true